CC = gcc
CFLAGS = -Wall -Wextra -pthread
LDFLAGS = -pthread

all: server client

server: server.c common.h
	$(CC) $(CFLAGS) server.c -o server $(LDFLAGS)

client: client.c common.h
	$(CC) $(CFLAGS) client.c -o client $(LDFLAGS)

clean:
	rm -f server client

run_server:
	./server

run_server2:
	./server 8081

run_server3:
	./server 8082

run_server4:
	./server 8083

run_client:
	./client --k 10 --mod 100 --servers servers.txt

.PHONY: all clean run_server run_server2 run_server3 run_server4 run_client
